// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdHGajGr4dkLtU8L1fpHqxTVdZjooAk3c',
    appId: '1:239423526085:web:8f61bc0479328cf3d90cac',
    messagingSenderId: '239423526085',
    projectId: 'emsproject-96c89',
    authDomain: 'emsproject-96c89.firebaseapp.com',
    storageBucket: 'emsproject-96c89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPUB5sGlXicvg5q-H3uPxBm10bhNs3NW8',
    appId: '1:239423526085:android:6480802c0c0dd7abd90cac',
    messagingSenderId: '239423526085',
    projectId: 'emsproject-96c89',
    storageBucket: 'emsproject-96c89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSgCGDs5NW9vwJGe2gC3t6HUGgTXOElv4',
    appId: '1:239423526085:ios:335c97cec206376cd90cac',
    messagingSenderId: '239423526085',
    projectId: 'emsproject-96c89',
    storageBucket: 'emsproject-96c89.appspot.com',
    iosBundleId: 'com.example.empprojectdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSgCGDs5NW9vwJGe2gC3t6HUGgTXOElv4',
    appId: '1:239423526085:ios:335c97cec206376cd90cac',
    messagingSenderId: '239423526085',
    projectId: 'emsproject-96c89',
    storageBucket: 'emsproject-96c89.appspot.com',
    iosBundleId: 'com.example.empprojectdemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdHGajGr4dkLtU8L1fpHqxTVdZjooAk3c',
    appId: '1:239423526085:web:e0546625f3e7f93bd90cac',
    messagingSenderId: '239423526085',
    projectId: 'emsproject-96c89',
    authDomain: 'emsproject-96c89.firebaseapp.com',
    storageBucket: 'emsproject-96c89.appspot.com',
  );
}
